export const Colors = {
  primary: '#0F8F7B',
  primaryDark: '#087263',
  primarySoft: '#DDF7F1',
  accent: '#FFB85C',
  accentSoft: '#FFF1DE',
  background: '#F6F8FA',
  backgroundDark: '#0C1116',
  surface: '#FFFFFF',
  surfaceDark: '#151C24',
  surfaceElevated: '#FFFFFF',
  surfaceElevatedDark: '#1B2530',
  card: '#FFFFFF',
  cardDark: '#151C24',
  text: '#17212B',
  textDark: '#F4F7FA',
  textMuted: '#6B7785',
  textMutedDark: '#9DAAB8',
  bubbleLeft: '#FFFFFF',
  bubbleLeftDark: '#1B2530',
  bubbleRight: '#DDF7F1',
  bubbleRightDark: '#075C52',
  border: '#E4E9EF',
  borderDark: '#26313D',
  input: '#EDF2F6',
  inputDark: '#202B36',
  success: '#18A957',
  error: '#E5484D',
  warning: '#F59E0B',
  online: '#21C063',
  overlay: 'rgba(15, 23, 42, 0.55)',
  shadow: '#0F172A',
};

export type ThemePalette = ReturnType<typeof getThemeColors>;

export const getThemeColors = (isDark: boolean) => ({
  primary: Colors.primary,
  primaryDark: Colors.primaryDark,
  primarySoft: isDark ? 'rgba(15, 143, 123, 0.18)' : Colors.primarySoft,
  accent: Colors.accent,
  accentSoft: isDark ? 'rgba(255, 184, 92, 0.16)' : Colors.accentSoft,
  background: isDark ? Colors.backgroundDark : Colors.background,
  surface: isDark ? Colors.surfaceDark : Colors.surface,
  surfaceElevated: isDark ? Colors.surfaceElevatedDark : Colors.surfaceElevated,
  card: isDark ? Colors.cardDark : Colors.card,
  text: isDark ? Colors.textDark : Colors.text,
  textMuted: isDark ? Colors.textMutedDark : Colors.textMuted,
  bubbleLeft: isDark ? Colors.bubbleLeftDark : Colors.bubbleLeft,
  bubbleRight: isDark ? Colors.bubbleRightDark : Colors.bubbleRight,
  border: isDark ? Colors.borderDark : Colors.border,
  input: isDark ? Colors.inputDark : Colors.input,
  success: Colors.success,
  error: Colors.error,
  warning: Colors.warning,
  online: Colors.online,
  shadow: Colors.shadow,
});
